Bayes_LinearData_DiffCov
Bayes_LinearData_SameCov
Bayes_Non_LinearData_SameCov
Bayes_Non_LinearData_SameCov
Bayes_OverlappingData_SameCov
Bayes_OverlappingData_DiffCov
NB_LinearData
NB_LinearData_DiffCov
NB_LinearData_SameCov
NB_Non_LinearData
NB_Non_LinearData_DiffCovariance
NB_Non_LinearData_SameCovariance
NB_OverlappingData
NB_OverlappingData_SameCov
NB_OveralappingData_DiffCov



